export const environment = {
  production: true,
  taskUrl: 'https://jsonplaceholder.typicode.com/todos',
  apiKey: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjIyODhiMTMwLTVjOWYtNDU2Zi1hOGJkLTA0YTU3NDNmNWNjZSIsImlhdCI6MTU3NTk5MDM1Nywic3ViIjoiZGV2ZWxvcGVyL2UxYmQ1OTEwLWE1ODEtMjZkNi05MGVhLTcwNTJjYWQyODE0YiIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiMzQuMjQxLjcuMjUyIl0sInR5cGUiOiJjbGllbnQifV19.uOAz4hFtPqVovA7ONYChAJG5cLY7pA6adeRTO13fv1V0oQo6c6rMn0sHqojuHXaQ0wY-aGsAP4qeADug1cwGnA'
};
