export const environment = {
  production: true,
  taskUrl: 'https://jsonplaceholder.typicode.com/todos',
  apiKey: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjMxOGJiNWMzLWViZDctNGU0OS04ZmEyLTQyZWVmNmNmNTNiYSIsImlhdCI6MTU3NDE4NjUyOSwic3ViIjoiZGV2ZWxvcGVyL2UxYmQ1OTEwLWE1ODEtMjZkNi05MGVhLTcwNTJjYWQyODE0YiIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiMC4wLjAuMCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.UJlNamDVlB8PYiYnJ62r78tQItvtKG19iu0idL5LrylClhO8tMuo5jj35izaDIeyt-9cNwj69wKVQuIvtBKlvQ'
};
